name: job_portal
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  lottie: ^3.3.1
  intl: ^0.20.2
  provider: ^6.0.5
  firebase_core: ^3.4.0
  cloud_firestore: ^5.3.0
  http: ^1.2.2
  firebase_storage: ^12.2.0
  firebase_auth: ^5.2.0
  google_fonts: any
  file_picker: ^8.1.2
  flutter_svg: ^2.0.17
  another_flushbar: ^1.12.30
  go_router: ^15.1.2
  pdf: ^3.10.4
  timeago: ^3.3.0
  cached_network_image: ^3.4.1
  printing: ^5.10.0
  google_sign_in: ^6.3.0
  fl_chart: ^1.0.0
  flutter_date_pickers: ^0.4.3
  rxdart: ^0.28.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/splash.webp
    - images/signup_recruiter.svg
    - images/signup_jobseeker.svg
    - images/login_recruiter.svg
    - images/login_jobseeker.svg
    - images/forgot.svg
    - images/recruiter_2.svg
    - images/success.json
    - images/MaterialIcons-Regular.ttf
